<?php
$pageTitle = 'Cargo Bay';
$extraCss = 'cargo.css';
$extraJs = 'cargo.js';

require_once __DIR__ . '/../includes/auth.php';
authRequire();

require_once __DIR__ . '/../includes/header.php';
?>

<!-- Balance Overview -->
<section class="cargo-header animate-in">
    <div class="cargo-header-left">
        <div class="cargo-section-tag">
            <span class="tag-marker" aria-hidden="true"></span>
            MODULE G5E — CARGO BAY SCHEMATIC
        </div>
        <h1 class="cargo-title">Equilibrage Station</h1>
    </div>
    <div class="cargo-header-right">
        <button class="iss-btn btn-reset" id="btn-reset" title="Remettre a zero la session">RESET</button>
        <div class="balance-meter">
            <div class="balance-label">EQUILIBRE GLOBAL</div>
            <div class="balance-bar-track">
                <div class="balance-bar-fill" id="balance-fill" style="width: 0%"></div>
            </div>
            <div class="balance-pct" id="balance-pct">0%</div>
        </div>
    </div>
</section>

<!-- Cargo Bay Schematic -->
<section class="cargo-schematic-wrapper animate-in" style="animation-delay: 0.1s">
    <div class="iss-panel">
        <div class="panel-header">
            <div class="panel-header-marker" aria-hidden="true"></div>
            <h2 class="panel-title">Schema Cargo</h2>
            <span class="panel-subtitle">CROSS-SECTION VIEW</span>
        </div>

        <div class="schematic-container">
            <!-- Blueprint grid background -->
            <div class="blueprint-grid" aria-hidden="true"></div>

            <!-- Ruler (horizontal, 10-80cm) -->
            <div class="ruler" id="ruler">
                <div class="ruler-track">
                    <!-- Ticks generated by JS -->
                </div>
                <div class="ruler-labels" id="ruler-labels"></div>
            </div>

            <!-- Target zones (4 steps) -->
            <div class="target-zones" id="target-zones"></div>

            <!-- Live sensor indicator -->
            <div class="sensor-line" id="sensor-line">
                <div class="sensor-line-beam"></div>
                <div class="sensor-line-head"></div>
                <div class="sensor-line-label" id="sensor-line-label">--</div>
            </div>

            <!-- Cargo items (4 objects) -->
            <div class="cargo-items" id="cargo-items"></div>

            <!-- Sensor origin marker -->
            <div class="sensor-origin">
                <div class="sensor-origin-icon">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" aria-hidden="true">
                        <path d="M12 2L12 6M12 18L12 22M2 12L6 12M18 12L22 12" stroke="currentColor" stroke-width="1.5"/>
                        <circle cx="12" cy="12" r="4" stroke="currentColor" stroke-width="1.5"/>
                        <circle cx="12" cy="12" r="8" stroke="currentColor" stroke-width="0.5" opacity="0.4"/>
                    </svg>
                </div>
                <div class="sensor-origin-label">CAPTEUR IR</div>
            </div>
        </div>

        <!-- Hold progress bar -->
        <div class="hold-bar-wrapper" id="hold-bar-wrapper">
            <div class="hold-bar-label">
                <span class="hold-bar-title">MAINTENIR EN ZONE</span>
                <span class="hold-bar-time" id="hold-bar-time">0.0 / 3.0s</span>
            </div>
            <div class="hold-bar-track">
                <div class="hold-bar-fill" id="hold-bar-fill" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" aria-label="Temps de maintien en zone"></div>
            </div>
        </div>

        <!-- Steps detail cards -->
        <div class="steps-cards" id="steps-cards"></div>
    </div>
</section>

<!-- Chart.js Historical Graph -->
<section class="cargo-chart-wrapper animate-in" style="animation-delay: 0.2s">
    <div class="iss-panel">
        <div class="panel-header">
            <div class="panel-header-marker" aria-hidden="true"></div>
            <h2 class="panel-title">Historique Capteur</h2>
            <div class="chart-period-btns">
                <button class="period-btn active" data-period="5min">5 MIN</button>
                <button class="period-btn" data-period="15min">15 MIN</button>
                <button class="period-btn" data-period="1h">1 H</button>
                <button class="period-btn" data-period="6h">6 H</button>
                <button class="period-btn" data-period="24h">24 H</button>
            </div>
        </div>

        <div class="chart-container">
            <canvas id="history-chart" aria-label="Graphique historique des mesures du capteur de distance" role="img"></canvas>
        </div>

        <div class="chart-footer">
            <div class="chart-stat">
                <span class="chart-stat-label">POINTS</span>
                <span class="chart-stat-value" id="chart-points">0</span>
            </div>
            <div class="chart-stat">
                <span class="chart-stat-label">PERIODE</span>
                <span class="chart-stat-value" id="chart-period">5 MIN</span>
            </div>
        </div>
    </div>
</section>

<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>

<?php require_once __DIR__ . '/../includes/footer.php'; ?>
